# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tic_tac_toe_pb2 as tic__tac__toe__pb2


class TicTacToeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartGame = channel.unary_unary(
                '/TicTacToe/StartGame',
                request_serializer=tic__tac__toe__pb2.StartGameRequest.SerializeToString,
                response_deserializer=tic__tac__toe__pb2.StartGameResponse.FromString,
                )
        self.LeaderElection = channel.unary_unary(
                '/TicTacToe/LeaderElection',
                request_serializer=tic__tac__toe__pb2.LeaderElectionRequest.SerializeToString,
                response_deserializer=tic__tac__toe__pb2.LeaderElectionResponse.FromString,
                )
        self.BerkleyTimeSync = channel.unary_unary(
                '/TicTacToe/BerkleyTimeSync',
                request_serializer=tic__tac__toe__pb2.BerkleyTimeSyncRequest.SerializeToString,
                response_deserializer=tic__tac__toe__pb2.BerkleyTimeSyncResponse.FromString,
                )
        self.SetSymbol = channel.unary_unary(
                '/TicTacToe/SetSymbol',
                request_serializer=tic__tac__toe__pb2.SetSymbolRequest.SerializeToString,
                response_deserializer=tic__tac__toe__pb2.SetSymbolResponse.FromString,
                )
        self.ListBoard = channel.unary_unary(
                '/TicTacToe/ListBoard',
                request_serializer=tic__tac__toe__pb2.ListBoardRequest.SerializeToString,
                response_deserializer=tic__tac__toe__pb2.ListBoardResponse.FromString,
                )
        self.SetNodeTime = channel.unary_unary(
                '/TicTacToe/SetNodeTime',
                request_serializer=tic__tac__toe__pb2.SetNodeTimeRequest.SerializeToString,
                response_deserializer=tic__tac__toe__pb2.SetNodeTimeResponse.FromString,
                )
        self.SetTimeOut = channel.unary_unary(
                '/TicTacToe/SetTimeOut',
                request_serializer=tic__tac__toe__pb2.SetTimeOutRequest.SerializeToString,
                response_deserializer=tic__tac__toe__pb2.SetTimeOutResponse.FromString,
                )
        self.CheckTimeOut = channel.unary_unary(
                '/TicTacToe/CheckTimeOut',
                request_serializer=tic__tac__toe__pb2.CheckTimeOutRequest.SerializeToString,
                response_deserializer=tic__tac__toe__pb2.CheckTimeoutResponse.FromString,
                )


class TicTacToeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaderElection(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BerkleyTimeSync(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetSymbol(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListBoard(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNodeTime(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetTimeOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckTimeOut(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicTacToeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=tic__tac__toe__pb2.StartGameRequest.FromString,
                    response_serializer=tic__tac__toe__pb2.StartGameResponse.SerializeToString,
            ),
            'LeaderElection': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaderElection,
                    request_deserializer=tic__tac__toe__pb2.LeaderElectionRequest.FromString,
                    response_serializer=tic__tac__toe__pb2.LeaderElectionResponse.SerializeToString,
            ),
            'BerkleyTimeSync': grpc.unary_unary_rpc_method_handler(
                    servicer.BerkleyTimeSync,
                    request_deserializer=tic__tac__toe__pb2.BerkleyTimeSyncRequest.FromString,
                    response_serializer=tic__tac__toe__pb2.BerkleyTimeSyncResponse.SerializeToString,
            ),
            'SetSymbol': grpc.unary_unary_rpc_method_handler(
                    servicer.SetSymbol,
                    request_deserializer=tic__tac__toe__pb2.SetSymbolRequest.FromString,
                    response_serializer=tic__tac__toe__pb2.SetSymbolResponse.SerializeToString,
            ),
            'ListBoard': grpc.unary_unary_rpc_method_handler(
                    servicer.ListBoard,
                    request_deserializer=tic__tac__toe__pb2.ListBoardRequest.FromString,
                    response_serializer=tic__tac__toe__pb2.ListBoardResponse.SerializeToString,
            ),
            'SetNodeTime': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNodeTime,
                    request_deserializer=tic__tac__toe__pb2.SetNodeTimeRequest.FromString,
                    response_serializer=tic__tac__toe__pb2.SetNodeTimeResponse.SerializeToString,
            ),
            'SetTimeOut': grpc.unary_unary_rpc_method_handler(
                    servicer.SetTimeOut,
                    request_deserializer=tic__tac__toe__pb2.SetTimeOutRequest.FromString,
                    response_serializer=tic__tac__toe__pb2.SetTimeOutResponse.SerializeToString,
            ),
            'CheckTimeOut': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckTimeOut,
                    request_deserializer=tic__tac__toe__pb2.CheckTimeOutRequest.FromString,
                    response_serializer=tic__tac__toe__pb2.CheckTimeoutResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TicTacToe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TicTacToe(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/StartGame',
            tic__tac__toe__pb2.StartGameRequest.SerializeToString,
            tic__tac__toe__pb2.StartGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaderElection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/LeaderElection',
            tic__tac__toe__pb2.LeaderElectionRequest.SerializeToString,
            tic__tac__toe__pb2.LeaderElectionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def BerkleyTimeSync(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/BerkleyTimeSync',
            tic__tac__toe__pb2.BerkleyTimeSyncRequest.SerializeToString,
            tic__tac__toe__pb2.BerkleyTimeSyncResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetSymbol(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/SetSymbol',
            tic__tac__toe__pb2.SetSymbolRequest.SerializeToString,
            tic__tac__toe__pb2.SetSymbolResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListBoard(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/ListBoard',
            tic__tac__toe__pb2.ListBoardRequest.SerializeToString,
            tic__tac__toe__pb2.ListBoardResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetNodeTime(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/SetNodeTime',
            tic__tac__toe__pb2.SetNodeTimeRequest.SerializeToString,
            tic__tac__toe__pb2.SetNodeTimeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetTimeOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/SetTimeOut',
            tic__tac__toe__pb2.SetTimeOutRequest.SerializeToString,
            tic__tac__toe__pb2.SetTimeOutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckTimeOut(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/CheckTimeOut',
            tic__tac__toe__pb2.CheckTimeOutRequest.SerializeToString,
            tic__tac__toe__pb2.CheckTimeoutResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
